server:
  port: 8081

spring:
  application:
    name: metrics-collector
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        batch.size: 65536

kafka:
  topics:
    external-data: external.data.raw

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.metrics.collector: INFO
    org.springframework.kafka: WARN
